[common]
base_url = https://www.saucedemo.com
# browser = edge
# browser = firefox_invalid
; Test with these two browsers and verify that the app works when edge used and displays value error when invalid is entered
browser = chrome  
implicit_wait = 10
explicit_wait = 20

[credentials]
standard_user = standard_user
locked_out_user = locked_out_user
password = secret_sauce