[pytest]

# Test configuration for pytest
testpaths = tests
python_files = test_*.py
python_functions = test_*

# Command-Line Options (addopts)
# Automatically runs with verbose output, extra test summary info, and generates HTML/Allure reports
addopts = 
    -v 
    -s
    --html=reports/report.html
    --self-contained-html
    --alluredir=reports/allure-results

# Markers
markers =
    smoke: mark a test as a smoke test
    regression: mark a test as a regression test
    api: mark a test as an API test
    negative: mark a test as a negative test

# Live Logging Configuration
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S