# Acts as settings menu
[API]
BASE_URL = https://jsonplaceholder.typicode.com
timeout = 10
posts_endpoint = /posts
users_endpoint = /users

[HEADERS]
content-type = application/json
Accept = application/json

[LOGGING]
log_level = INFO
log_file = logs/framework.log

[REPORTS]
html_report_dir = reports/report.html
allure_results_dir = reports/allure-results