[pytest]
# Automatically add command-line options for reporting and verbose execution
addopts = -s -v --html=reports/html/report.html --self-contained-html --alluredir=allure-results

# Pytest CLI logging configuration
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] (%(filename)s:%(lineno)d) - %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

# Custom markers
markers =
    smoke: Smoke tests
    regression: Regression tests